### ISSUE TITLE
vision: issue with webDetect

### ISSUE THREAD

**Issue by lukaszraczylo** [GoogleCloudPlatform/golang-samples#794] opened 2019-03-11 11:58 UTC
Possibly related to #306 .

Running code from example:
```	
        ctxWeb := context.Background()
	clientWeb, err := vision.NewImageAnnotatorClient(ctxWeb)
	if err != nil {
		Log.Warn("Can't set up label client", err)
		return false, []string{""}
	}
	imageWeb, err := vision.NewImageFromReader(imageReader)
	if err != nil {
		Log.Warn("Can't accept reader image: ", err.Error())
		return false, []string{}
	}
	web, err := clientWeb.DetectWeb(ctxWeb, imageWeb, nil)
	if err != nil {
		Log.Warn("Can't run label detection on image: ", err.Error())
		return false, []string{}
	}
```

Dies with ```rpc error: code = InvalidArgument desc = Request must specify image and features.```

**Comment by tbpg** [comment] 2019-06-11 14:29
I just tried this locally and it worked. Would you mind updating to the latest version of the client library?

**Comment by tbpg** [comment] 2019-07-19 11:14
Closing this as cannot reproduce. Feel free to open another issue if there's a sample that's not working. Thank you for filing this one - I hope you got it working!

**Closed by tbpg** 2019-07-19 11:14 UTC
