### ISSUE TITLE
speech: segmentation fault while using model selection

### ISSUE THREAD

**Issue by oscar-defelice** [GoogleCloudPlatform/golang-samples#1704] opened 2020-09-14 15:07 UTC
# My versions

```bash
go version go1.15 darwin/amd64
```
 and I am running on a mac OS.
```bash
 % sw_vers -productVersion
10.15.6
```

I am using the code in the `snippets/model_selection.go` file.

## My code

```go
package main

import(
  "fmt"
  "golang.org/x/net/context"
  "io"
  "io/ioutil"
  speech "cloud.google.com/go/speech/apiv1"
  speechpb "google.golang.org/genproto/googleapis/cloud/speech/v1"
  "strings"
)

var path string = "Audio/ClementinePizzaAudio.wav"

func ModelSelection(w io.Writer, path string) error {
	ctx := context.Background()

	client, err := speech.NewClient(ctx)
	if err != nil {
		return fmt.Errorf("NewClient: %v", err)
	}

	// path = "Audio/ClementinePizzaAudio.wav"
	data, err := ioutil.ReadFile(path)
	if err != nil {
		return fmt.Errorf("ReadFile: %v", err)
	}

	req := &speechpb.RecognizeRequest{
		Config: &speechpb.RecognitionConfig{
			Encoding:        speechpb.RecognitionConfig_LINEAR16,
			SampleRateHertz: 48000,
			LanguageCode:    "en-US",
			Model:           "phone_call",
		},
		Audio: &speechpb.RecognitionAudio{
			AudioSource: &speechpb.RecognitionAudio_Content{Content: data},
		},
	}

  fmt.Printf("\n Good until here\n")

	resp, err := client.Recognize(ctx, req)
	if err != nil {
		return fmt.Errorf("Recognize: %v", err)
	} else {
    fmt.Printf("this is resp %s", resp)
  }

	 for i, result := range resp.Results {
	 	fmt.Fprintf(w, "%s\n", strings.Repeat("-", 20))
	 	fmt.Fprintf(w, "Result %d\n", i+1)
	 	for j, alternative := range result.Alternatives {
	 		fmt.Fprintf(w, "Alternative %d: %s\n", j+1, alternative.Transcript)
	 }
	}
	return nil
}

func main () {
  fmt.Printf("Start listening to audio in %s", path)
  w := bufio.NewWriter(os.Stdout)

  err := ModelSelection(w ,path); if err != nil {
    fmt.Println(err)
  }
}
```

## The issue

I got a segmentation fault code, apparently due to a go routine going out of memory.

```bash
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x10dff37]

goroutine 1 [running]:
fmt.Fprintf(0x0, 0x0, 0x166da44, 0x3, 0xc000c7fec8, 0x1, 0x1, 0xd0, 0x0, 0x0)
	/usr/local/go/src/fmt/print.go:205 +0x77
main.ModelSelection(0x0, 0x0, 0x167e3c4, 0x1e, 0xc00035ff68, 0x1)
	/Users/oscar/Documents/LaJavaness/Enedis/speechgotext/transcript.go:75 +0x633
main.main()
	/Users/oscar/Documents/LaJavaness/Enedis/speechgotext/transcript.go:87 +0xdc
exit status 2
```

## Note

If I comment out the `for i, result {...}` last loop, right before the `return nil`. I got a print of the result object as I expect.
So it seems to be an issue with the res formatting, maybe.

**Comment by tbpg** [comment] 2020-09-15 12:48
Hi there. This is caused by a nil pointer dereference. Basically, that means you're trying to do something with a `nil` value, but you can't. For example, if `result` is `nil`, you can't do `result.Alternatives`. It's not caused by running out of memory.

The line numbers in the panic output tell you which line is causing the problem. Look for a `foo.Bar` call on that line, and `foo` is the thing that is `nil`. Try just printing `foo` instead to see what's happening.

Also, side note, you should be able to add a Go plugin to your editor that will automatically format it with `gofmt` on save. It's fast and easy -- highly recommend. All Go code should be formatted with `gofmt`.

**Comment by tbpg** [comment] 2020-11-21 15:47
Closing as I think this is settled. I hope you got it all working!

**Closed by tbpg** 2020-11-21 15:47 UTC
Labels: api: speech, samples, type: question
