### ISSUE TITLE
gcloud functions deploy fails with useless error message

### ISSUE THREAD

**Issue by lukepuplett** [GoogleCloudPlatform/golang-samples#1272] opened 2020-03-10 17:25 UTC
Hey, I'm new to GCP and Golang but 23 years exp in Microsoft land. I'm following the tutorial here:

https://cloud.google.com/functions/docs/first-go

But upon deploy, after 49 seconds, I receive this error. Note I changed the name of the handler func compare with the tutorial.

```
PS C:\DATA\go\src\iploc> gcloud functions deploy TestHTTPTrigger --runtime go113 --trigger-http --allow-unauthenticated --verbosity=debug
DEBUG: Running [gcloud.functions.deploy] with arguments: [--allow-unauthenticated: "True", --runtime: "go113", --trigger-http: "True", --verbosity: "debug", NAME: "TestHTTPTrigger"]
INFO: Not using ignore file.
INFO: Not using ignore file.
Deploying function (may take a while - up to 2 minutes)...failed.
DEBUG: (gcloud.functions.deploy) OperationError: code=3, message=Build failed:
Traceback (most recent call last):
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\lib\googlecloudsdk\calliope\cli.py", line 983, in Execute
    resources = calliope_command.Run(cli=self, args=args)
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\lib\googlecloudsdk\calliope\backend.py", line 807, in Run
    resources = command_instance.Run(args)
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\lib\surface\functions\deploy.py", line 343, in Run
    return _Run(args, track=self.ReleaseTrack())
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\lib\surface\functions\deploy.py", line 297, in _Run
    on_every_poll=[TryToLogStackdriverURL])
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\lib\googlecloudsdk\api_lib\functions\util.py", line 318, in CatchHTTPErrorRaiseHTTPExceptionFn
    return func(*args, **kwargs)
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\lib\googlecloudsdk\api_lib\functions\util.py", line 369, in WaitForFunctionUpdateOperation
    on_every_poll=on_every_poll)
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\lib\googlecloudsdk\api_lib\functions\operations.py", line 151, in Wait
    on_every_poll)
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\lib\googlecloudsdk\api_lib\functions\operations.py", line 121, in _WaitForOperation
    sleep_ms=SLEEP_MS)
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\lib\googlecloudsdk\core\util\retry.py", line 219, in RetryOnResult
    result = func(*args, **kwargs)
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\lib\googlecloudsdk\api_lib\functions\operations.py", line 73, in _GetOperationStatus
    raise exceptions.FunctionsError(OperationErrorToString(op.error))
FunctionsError: OperationError: code=3, message=Build failed:
ERROR: (gcloud.functions.deploy) OperationError: code=3, message=Build failed:
PS C:\DATA\go\src\iploc>
```

Some weeks ago I did manage to write and deploy a little test Function on GCP though I don't remember a great deal about what I did. I do know two things;

1. That codebase looks different, it has a `./cmd/main.go` file with some code to register the handler func from the trigger source go file.

1. I received an email from GCP about enabling Cloud Build API on my project, which the tutorial doesn't mention but I did anyway.

I'm in a big rush, the intention was to write a G Function to tell me the location of a caller's IP but I'll likely just buy access to the Microsoft Maps Geolocation API in the meantime because I need stuff to just work and get out of my way and troubleshooting time is way more expensive than renting an API.

Cheers bye.

**Comment by codyoss** [comment] 2020-03-11 15:09
If you run `go build` on your on your Go code does it build?

**Comment by lukepuplett** [comment] 2020-03-11 20:24
Hey Cody, yep. As in, it returns no output, and I think the design ethos is "no news is good news" ;)

**Comment by tbpg** [comment] 2020-03-18 19:13
I just tried this on my computer (not Windows) and didn't have any issues, with and without modifying the function name.

Were you able to get it working without changing the name of the function?

**Comment by lukepuplett** [comment] 2020-03-18 21:58
Firstly, sincere thanks for trying. If I get a moment tomorrow I'll look again, but I'm time short and tbh, I'm finding it hard to concentrate between the pandemic and kids.

From that trace, it smells like the build is performed in the cloud and upon failure, the API isn't marshalling enough detail back through the CLI to me to allow me to take corrective action.

**Comment by tbpg** [comment] 2020-03-19 17:21
That definitely seems like the underlying problem. We're working on fixing it.

If you have a support contract, if you open a ticket we can take a look at the underlying build logs and let you know what the problem is. Otherwise, hopefully the unedited version will work for you...

**Comment by tbpg** [comment] 2020-10-06 13:35
Closing this as we don't have further updates for this particular issue.

**Closed by tbpg** 2020-10-06 13:35 UTC
Labels: api: cloudfunctions, sample, samples, type: question
