### ISSUE TITLE
The deployment is broken on App Engine flexible for Go

### ISSUE THREAD

**Issue by cybercent** [GoogleCloudPlatform/golang-samples#1799] opened 2020-10-25 14:18 UTC
Not sure is the best place to post this issue.

The deployment is broken on App Engine flexible for Go.

```
Step #1: error building image: getting stage builder for stage 0: MANIFEST_UNKNOWN: "Manifest with digest 'sha256:884ac2144c3ee154bd67271e99bc6ef00f430092750167729b0321ab55fde5ec' has media type 'application/vnd.docker.distribution.manifest.list.v2+json', but client accepts 'application/vnd.docker.distribution.manifest.v2+json'."
```

**Comment by gabriel** [comment] 2020-10-26 03:19
I'm also unable to deploy go1.14 or go1.15 in the appengine flex environment with this same error:

```
Step #0: dc59566c26e6: Pull complete
Step #0: Digest: sha256:9bb092bd9c8d6924d683663953c54d7dd068eabd80d6853ace0fd7f1186fff84
Step #0: Status: Downloaded newer image for gcr.io/gcp-runtimes/go1-builder@sha256:9bb092bd9c8d6924d683663953c54d7dd068eabd80d6853ace0fd7f1186fff84
Step #0: gcr.io/gcp-runtimes/go1-builder@sha256:9bb092bd9c8d6924d683663953c54d7dd068eabd80d6853ace0fd7f1186fff84
Finished Step #0
Starting Step #1
Step #1: Already have image (with digest): gcr.io/kaniko-project/executor@sha256:f87c11770a4d3ed33436508d206c584812cd656e6ed08eda1cff5c1ee44f5870
Step #1: INFO[0000] Downloading base image gcr.io/distroless/base@sha256:884ac2144c3ee154bd67271e99bc6ef00f430092750167729b0321ab55fde5ec 
Step #1: error building image: getting stage builder for stage 0: MANIFEST_UNKNOWN: "Manifest with digest 'sha256:884ac2144c3ee154bd67271e99bc6ef00f430092750167729b0321ab55fde5ec' has media type 'application/vnd.docker.distribution.manifest.list.v2+json', but client accepts 'application/vnd.docker.distribution.manifest.v2+json'."
Finished Step #1
ERROR
ERROR: build step 1 "gcr.io/kaniko-project/executor@sha256:f87c11770a4d3ed33436508d206c584812cd656e6ed08eda1cff5c1ee44f5870" failed: step exited with non-zero status: 1
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

ERROR: (gcloud.app.deploy) Cloud build failed. Check logs at https://console.cloud.google.com/cloud-build/builds/7df10b69-72ad-465f-ba49-54fb729c3f42?project=498351404878 Failure status: UNKNOWN: Error Response: [2] Build failed; check build logs for details
```

go1.13 works, but I need a more recent go...

**Comment by pavelpascari** [comment] 2020-10-27 13:08
I can confirm that using `runtime: go1.13` in the `app.yaml` does work.

**Comment by tbpg** [comment] 2020-10-27 18:32
Thanks for the report -- not sure what the cause is yet.

**Comment by ichili** [comment] 2020-10-27 18:53
For my deployments the issue is still present for any go runtime

**Comment by cybercent** [comment] 2020-10-28 14:46
Go 1.13 worked only for the first deployment, it will break too once you deploy again.

**Comment by cybercent** [comment] 2020-10-28 14:49
@grayside @tbpg what is the ETA on this?
3 days we can't deploy on GAE Flex!

**Comment by albeebe** [comment] 2020-10-28 15:12
changing the runtime did not work for me when deploying an update to an existing service

**Comment by cybercent** [comment] 2020-10-28 15:34
I updated to the latest components:
```
gcloud components update
```
Now I get a new error: 
```
Step #0: can't load package: package .: no Go files in /workspace/staging.sBe0
```

**Comment by cybercent** [comment] 2020-10-28 17:10
https://issuetracker.google.com/issues/171756486

**Comment by sbuss** [comment] 2020-10-28 17:31
Thanks for the bug report, and sorry we missed it. We've escalated the issue and have a team working on resolving it now.

**Comment by sbuss** [comment] 2020-10-28 18:53
We have successfully rolled back the broken build. You will also need to downgrade to gcloud version 315.0.0, or upgrade to version 317.0.0 when it is released next week. You can change your gcloud version via:

`gcloud components update --version 315.0.0`

Please run that command and try deploying again.

**Comment by cybercent** [comment] 2020-10-28 22:43
Thanks, it works now.

**Comment by sbuss** [comment] 2020-10-28 22:54
@tbpg I don't have permissions to close this issue, but you can do so now.

**Comment by tbpg** [comment] 2020-10-28 23:20
Thanks, @sbuss!

**Closed by tbpg** 2020-10-28 23:20 UTC
Labels: api: appengine, priority: p1, samples, type: bug

**Comment by sbuss** [comment] 2020-10-28 23:50
Initial root cause analysis indicates that kaniko does not support manifest lists, which the distroless images recently(?) converted to. Moving discussion of that issue to https://github.com/GoogleContainerTools/kaniko/issues/1465.
